
[dags]
[dags.default]
template = '/home/airflow/airflow/include/dags_template/raw_to_bronze_incremental.py'
folder = '/home/airflow/airflow/dags/bronze/dock_opt/'


# [BEGIN bronze_opt_t_fatura] ---------------------------------------------------------------------
[dags.bronze_opt_t_fatura]
dag_id = "'bronze_opt_t_fatura'"
tags = "['fonte_opt', 'camada_bronze', 'processo_incremental']"
start_date = 'datetime(2023, 1, 10)'
dataset = "'bronze_opt_t_fatura'"
dataset_upstream = "['raw_opt_t_fatura']"

[dags.bronze_opt_t_fatura.default_args]
owner = 'matheus.rodrigues@fortbrasil.com.br'

[dags.bronze_opt_t_fatura.tasks_args]
adb = "'adb'"
path = "'dock_opt/t_fatura/'"
catalog = "'hml'"
schema = "'bronze'"
table = "'opt_t_fatura'"
# [END bronze_opt_t_fatura] -----------------------------------------------------------------------


# [BEGIN bronze_opt_t_transacaofatura] ------------------------------------------------------------
[dags.bronze_opt_t_transacaofatura]
dag_id = "'bronze_opt_t_transacaofatura'"
tags = "['fonte_opt', 'camada_bronze', 'processo_incremental']"
start_date = 'datetime(2023, 1, 10)'
dataset = "'bronze_opt_t_transacaofatura'"
dataset_upstream = "['raw_opt_t_transacaofatura']"

[dags.bronze_opt_t_transacaofatura.default_args]
owner = 'matheus.rodrigues@fortbrasil.com.br'

[dags.bronze_opt_t_transacaofatura.tasks_args]
adb = "'adb'"
path = "'dock_opt/t_transacaofatura/'"
catalog = "'hml'"
schema = "'bronze'"
table = "'opt_t_transacaofatura'"
# [END bronze_opt_t_transacaofatura] --------------------------------------------------------------


# [BEGIN bronze_opt_t_parcelamentofatura] ---------------------------------------------------------
[dags.bronze_opt_t_parcelamentofatura]
dag_id = "'bronze_opt_t_parcelamentofatura'"
tags = "['fonte_opt', 'camada_bronze', 'processo_incremental']"
start_date = 'datetime(2023, 1, 10)'
dataset = "'bronze_opt_t_parcelamentofatura'"
dataset_upstream = "['raw_opt_t_parcelamentofatura']"

[dags.bronze_opt_t_parcelamentofatura.default_args]
owner = 'matheus.rodrigues@fortbrasil.com.br'

[dags.bronze_opt_t_parcelamentofatura.tasks_args]
adb = "'adb'"
path = "'dock_opt/t_parcelamentofatura/'"
catalog = "'hml'"
schema = "'bronze'"
table = "'opt_t_parcelamentofatura'"
# [END bronze_opt_t_parcelamentofatura] -----------------------------------------------------------


# [BEGIN bronze_opt_t_eventocompra] ---------------------------------------------------------------
[dags.bronze_opt_t_eventocompra]
dag_id = "'bronze_opt_t_eventocompra'"
tags = "['fonte_opt', 'camada_bronze', 'processo_incremental']"
start_date = 'datetime(2023, 1, 10)'
dataset = "'bronze_opt_t_eventocompra'"
dataset_upstream = "['raw_opt_t_eventocompra']"

[dags.bronze_opt_t_eventocompra.default_args]
owner = 'matheus.rodrigues@fortbrasil.com.br'

[dags.bronze_opt_t_eventocompra.tasks_args]
adb = "'adb'"
path = "'dock_opt/t_eventocompra/'"
catalog = "'hml'"
schema = "'bronze'"
table = "'opt_t_eventocompra'"
# [END bronze_opt_t_eventocompra] -----------------------------------------------------------------


# [BEGIN bronze_opt_t_eventopagamento] ------------------------------------------------------------
[dags.bronze_opt_t_eventopagamento]
dag_id = "'bronze_opt_t_eventopagamento'"
tags = "['fonte_opt', 'camada_bronze', 'processo_incremental']"
start_date = 'datetime(2023, 1, 23)'
dataset = "'bronze_opt_t_eventopagamento'"
dataset_upstream = "['raw_opt_t_eventopagamento']"

[dags.bronze_opt_t_eventopagamento.default_args]
owner = 'matheus.rodrigues@fortbrasil.com.br'

[dags.bronze_opt_t_eventopagamento.tasks_args]
adb = "'adb'"
path = "'dock_opt/t_eventopagamento/'"
catalog = "'hml'"
schema = "'bronze'"
table = "'opt_t_eventopagamento'"
# [END bronze_opt_t_eventopagamento] --------------------------------------------------------------


# [BEGIN bronze_opt_t_eventoacordoativo] ----------------------------------------------------------
[dags.bronze_opt_t_eventoacordoativo]
dag_id = "'bronze_opt_t_eventoacordoativo'"
tags = "['fonte_opt', 'camada_bronze', 'processo_incremental']"
start_date = 'datetime(2023, 1, 23)'
dataset = "'bronze_opt_t_eventoacordoativo'"
dataset_upstream = "['raw_opt_t_eventoacordoativo']"

[dags.bronze_opt_t_eventoacordoativo.default_args]
owner = 'matheus.rodrigues@fortbrasil.com.br'

[dags.bronze_opt_t_eventoacordoativo.tasks_args]
adb = "'adb'"
path = "'dock_opt/t_eventoacordoativo/'"
catalog = "'hml'"
schema = "'bronze'"
table = "'opt_t_eventoacordoativo'"
# [END bronze_opt_t_eventoacordoativo] ------------------------------------------------------------
